### PR TITLE
Add contact form

### PR DESCRIPTION
**Pull request by abeltsew**
Added A contact form
Setup the Backend to receive the form Inputs

### CODE REVIEW

**Review by franclobo — COMMENTED** [review]
Hi @abeltsew, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors. ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by franclobo** [comment]
# ⚠️ 🚨⚠️ 🚨⚠️   ALERT ⚠️ 🚨⚠️ 🚨⚠️  
Hi, @abeltsew,

As I communicated with you on Slack I marked your project as approved in the dashboard by ERROR, please wait until Student Succes update manually the status of the activity. Kindly undo the merge action.

**Comment by abeltsew** [comment]
Hi @franclobo,

I have reverted the merge and managed to create a new pull request ready to be reviewed, it's pull number 6 FYI.

**Comment by enniopo** [comment]
Hi @abeltsew your dashboard has been updated and you can now submit a new review request. Thanks and apologies for the inconvenience.

**Pull request merged**
